<?php

namespace Emova\IelraBundle\Repository;

/**
 * OrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class OrderLineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $statut
     * @return array
     */
    public function getOrderLineByStatut($statut)
    {
        $query = $this->createQueryBuilder('o')
            ->where('o.statut = :statut')

            ->setParameter('statut', $statut)
            ->orderBy('o.dateFacturation', 'ASC')
            ->getQuery();

        $orders = $query->setMaxResults(5)->getResult();
        return $orders;
    }
    public function getOrderLineBy($statut)
    {
        $query = $this->createQueryBuilder('o')
            ->where('o.statut = :statut')

            ->setParameter('statut', $statut)
            ->orderBy('o.dateFacturation', 'ASC')
            ->getQuery();

        $orders = $query->getResult();
        return $orders;
    }

    public function countNumberCommande()
    {
        $query = $this->createQueryBuilder('com')
            ->select('COUNT(com.statut), com.statut')
            ->groupBy('com.statut')
            ->getQuery()
            ->getScalarResult();
        return $query;
    }

}
